version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --innodb-file-per-table=1
      - --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MARIADB_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  redis-cache:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_cache_data:/data
    restart: unless-stopped

  redis-queue:
    image: redis:6.2-alpine  
    command: redis-server --appendonly yes
    volumes:
      - redis_queue_data:/data
    restart: unless-stopped

  redis-socketio:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_socketio_data:/data
    restart: unless-stopped

  erpnext:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    depends_on:
      mariadb:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started  
      redis-socketio:
        condition: service_started
    environment:
      MARIADB_HOST: mariadb
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      SITE_NAME: ${SITE_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      FRAPPE_VERSION: ${ERPNEXT_VERSION}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      timeout: 10s
      retries: 10

volumes:
  mariadb_data:
  redis_cache_data:
  redis_queue_data:
  redis_socketio_data:
  sites:
  assets:
