# ==============================================================================
# Docker Compose para Frappe/ERPNext - Abordagem Completa e Confiável
# Baseado no repositório frappe_docker
# ==============================================================================
version: "3.8"

volumes:
  sites:
  assets:
  db-data:

networks:
  dokploy-network:
    external: true
  default:
    driver: bridge

services:
  # O serviço principal do Frappe, que tem todos os comandos
  frappe:
    image: frappe/bench:latest
    restart: on-failure
    command: ["sleep", "infinity"] # Apenas mantém o contêiner rodando
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - DB_ROOT_PASSWORD=SUA_SENHA_SECRETA_ROOT # Use a mesma do serviço 'db'
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
    networks:
      - default

  # O proxy Nginx que direciona o tráfego
  frontend:
    image: frappe/frappe-nginx:latest
    restart: on-failure
    expose:
      - 80
    environment:
      - BACKEND=frappe:8000
      - SOCKETIO=frappe:9000
      - UPSTREAM_REAL_IP_ADDRESS=172.18.0.0/16
      - UPSTREAM_REAL_IP_RECURSIVE=on
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frappe-multisite.rule=Host(`erp.portela.top` ) || Host(`crm.portela.top`)"
      - "traefik.http.routers.frappe-multisite.entrypoints=websecure"
      - "traefik.http.routers.frappe-multisite.tls.certresolver=letsencrypt"
      - "traefik.http.services.frappe-multisite.loadbalancer.server.port=80"
    networks:
      - dokploy-network
      - default

  # Banco de dados
  db:
    image: mariadb:10.6
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'Ewqdsacxz@2025' # Use a mesma do serviço 'frappe'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default

  # Redis
  redis-queue:
    image: redis:6.2-alpine
    restart: on-failure
    networks:
      - default

  redis-cache:
    image: redis:6.2-alpine
    restart: on-failure
    networks:
      - default
