cat > docker-compose.yml << 'EOF'
version: "3.8"

services:
  erpnext:
    image: frappe/erpnext:v15.15.0
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      MARIADB_HOST: mariadb
      MARIADB_ROOT_PASSWORD: Ewqdsacxz2025
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      SITE_NAME: erp.portela.top
      ADMIN_PASSWORD: Ewqdsacxz@@2025@@
      INSTALL_APPS: erpnext
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
    command: sleep infinity

volumes:
  sites:
    external: true
    name: erp-portela-evfb6b_sites
  assets:
    external: true
    name: erp-portela-evfb6b_assets

networks:
  default:
    external: true
    name: erp-portela-evfb6b_default
EOF
